### PR TITLE
Fix Bug : #54, #69

### PR DESCRIPTION
**Pull request by vavadevds**
The problem is in 'await PerformHandshakeAsync(ipc)'.
The ipc.Once("components:init") is never called.

Finally, I found a solution to the problem,
The problem was coming from WebWindow.Native.dll.

### CODE REVIEW

**Comment by vavadevds** [comment]
Hi please note that you need to make manual changes in this file : (packages\Microsoft.Web.WebView2.0.8.355\build\native\include\WebView2.h)

From this :

 MIDL_INTERFACE("E0618CDD-4947-4F58-802C-FC1F20BD4274")
    IWebView2CreateWebViewCompletedHandler : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Invoke( 
            HRESULT result,
            IWebView2WebView *webView) = 0;
        
    };

To This :

 MIDL_INTERFACE("E0618CDD-4947-4F58-802C-FC1F20BD4274")
    IWebView2CreateWebViewCompletedHandler : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Invoke( 
            HRESULT result,
            IWebView2WebView5 *webView) = 0;
        
    };

**Comment by r-ml** [comment]
for the pipeline to complete successfully, you'd need to change the version in the `azure-pipelines.yml`
to `3.1.101`

**Comment by 3GDXC** [comment]
@vavadevds this PR dosn't work for me; @ScottKane PR works with earlier versions of blazor and addressed the issues without including breaking changes that current blazor has; longer term IMHO these breaking changes in blazor needs to have some coordination with WedWindow given the dependencies; until the WebWindow can be fully updated.  fixes should be done on a seperate PR to MAJOR version updates where breaking changes are introduced.

**Comment by vavadevds** [comment]
Hi @3GDXC Please can you give some detail about error you get when you try to run my PR,
Thank you.

**Pull request closed without merging**
